name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Issue has not had any activity for 60 days'
        stale-pr-message: 'Pull Request has not had any activity for 60 days'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
